name: Setup
description: sets up helm lint and testing environment
inputs:
  create-kind-cluster: # id of input
    description: "Whether or not to create a kind cluster during setup"
    required: true
    default: "false"
  helm-version:
    description: "The helm version to be used when setting up"
    required: false
    default: "v3.9.4"
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: ${{ inputs.helm-version }}

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.0
